# Generated by Django 3.1.4 on 2020-12-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('auther', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50)),
                ('progress', models.PositiveSmallIntegerField()),
                ('duedate', models.DateField()),
                ('complete', models.BooleanField()),
            ],
        ),
    ]
